{% set name = "cyclonedds" %}
{% set version = "0.10.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eclipse-cyclonedds/cyclonedds/archive/{{ version }}.tar.gz
    sha256: ec3ec898c52b02f939a969cd1a276e219420e5e8419b21cea276db35b4821848

build:
  number: 0
  skip: true  # [unix]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - maven
    - openjdk
    - ninja
  host:
    - openssl

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\ddsc.dll exit 1  # [win]

about:
  home: https://github.com/eclipse-cyclonedds/cyclonedds
  license: EPL-2.0
  license_file: LICENSE
  summary: |
    Eclipse Cyclone DDS

extra:
  recipe-maintainers:
    - seanyen
