{% set name = "cyclonedds" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eclipse-cyclonedds/cyclonedds/archive/V{{ version }}.tar.gz
    sha256: 40622c6ee9f785cc3b2f053615e94c28562085f18c2b3553c822d31a0efd0139

build:
  number: 0
  skip: true  # [win and vc<14 or unix]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - maven
    - openjdk
    - ninja
  host:
    - openssl
  run:
    - openssl

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\ddsc.dll exit 1  # [win]

about:
  home: https://github.com/eclipse-cyclonedds/cyclonedds
  license: EPL-2.0
  license_file: LICENSE
  summary: |
    Eclipse Cyclone DDS

extra:
  recipe-maintainers:
    - seanyen
