{% set name = "cyclonedds" %}
{% set version = "0.10.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eclipse-cyclonedds/cyclonedds/archive/{{ version }}.tar.gz
    sha256: fe7bb5a4348e31656a935f72dec909a7d2b0fcf10840614fb552f08eb2da8484

build:
  number: 0
  skip: true  # [unix]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - maven
    - openjdk
    - ninja
  host:
    - openssl

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\ddsc.dll exit 1  # [win]

about:
  home: https://github.com/eclipse-cyclonedds/cyclonedds
  license: EPL-2.0
  license_file: LICENSE
  summary: |
    Eclipse Cyclone DDS

extra:
  recipe-maintainers:
    - seanyen
